### ISSUE TITLE
HP and Damage Rework

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#19]
## General Goals and Explanation

- Massively reduce/remove damage and HP scaling. 
  - Also consider adding additional damage levels beyond Light Medium and Heavy, or indeed alter the distribution of these values.
  - Example solution: Set Light/Medium/Heavy to always be 2/4/6. Set HP to be 2*CON Value. However, this does not solve some of our issues. Anyone can still invest in CON and be tanky, and increasing main attack stat first is still more valuable than increasing CON. How do we make people choose between being tanky melee or squishy ranged? Can just abilities solve most of this?
  - Additional solution: As an additional part to character creation we have people choose if they want to be Tank, Damage, or Healing focused for example, each of which is exclusive and can only be chosen once at level 1. Tank focus would give say 20 extra HP, Damage would increase damage values to 3/6/9, and Healing might increase all healing output to 4/8/12 (if we'd even need a healing one, maybe damage and healing would be combined). This could be very very hard to balance and get right, and do players want to decide something like this at level 1 and be so different? It feels a bit weird to have this.
- Increase the difference in HP between a "tanky" and "non-tanky" character. And/or find better ways using abilities to enable the tanky characters to tank.
  - Tanking currently feels worse than avoiding damage, and is difficult to do by yourself, you need other support characters to give you the buffs or heals to enable your tanking.
  - Melee and tanking also feels worse than ranged as it is much less consistent and exposes you to damage.
  - As everyone has very similar health and resistance points there is a need for everyone to "tank" quite equally which can be good and bad as there is a balance to be struck here between making being a tank feel good, and requiring there to be a tank in the party to be a viable party. If no one has the ability to take damage, enemies that use ranged attacks could become very lethal for example.

**Comment by Jackington6600** [comment]
test

**Comment by Jackington6600** [comment]
like this?

**Comment by Jackington6600** [comment]
or completely separate issues

**Comment by Jackington6600** [comment]
Solution Summary:

HP & Damage levels are now set to provisionally Constitution*4 & 3/6/9.

This is roughly equivalent to lvl 5 with a buff to Con.

Every 2 levels, people get 2 points to put into 2 different stats (1 each).  Both points are required for every stat increase above 20.  This removes the hard max cap.

Starting attributes are reduced by a small amount (16-13?) - Also consider a lesser reduction.

**Comment by Jackington6600** [comment]
Strong suggestion to add a progression system in which every 5 levels a player character will decide between a few Legendary Traits - they will choose from the following (WIP):
- Increase your max HP by additional CON value. 
- Increase Light/Medium/Heavy by one step to increase damage and healing etc. e.g. 3/6/9 to 4/8/12.
- Gain 5 FORT resistance points. Can only be taken once.
- Gain 5 REFL resistance points. Can only be taken once.
- Gain 5 WILL resistance points. Can only be taken once.
- Gain +1 AC while wearing Light Armour and remove -5ft of the speed debuff. Can only be taken once.
- Gain +1 AC while wearing Heavy Armour and remove -5ft of the speed debuff. Can be taken up to 2 times.
- Gain 1 additional use of every ability.

**Comment by Jackington6600** [comment]
Warrior Core ability will need altering/limiting - such as leaving it as 2HP per level, and max of 5-10 levels.

**Comment by PTruscott** [comment]
>Gain +1 AC while wearing Light Armour and remove -5ft of the speed debuff. Can only be taken once.

Change to any armour?  Then Heavy is the same and each can be taken just once
