### ISSUE TITLE
Team Coordination

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#21]
- Want a way to encourage more team work and coordination in combat, kinda like gloomhaven does. Perhaps achieve this with a top of the round planning thing, or a grouped initiative system. The prior could just feel a bit disconnected and extend combat duration significantly. The latter gets messy with condition durations and stuff, also leads more swingy fights.

**Comment by PTruscott** [comment]
The round where people discuss their plays seems to work reasonably well in person
