### ISSUE TITLE
Missing Big Abilities

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#22]
- Rolling to hit on big abilities such as AoEs and missing all targets/having no affect feels very bad. Not thought of a reasonable solution to this - potentially giving something back when this happens such as an ability use.

**Comment by PTruscott** [comment]
Wouldn't just rolling for each person you hit solve this?  Stops it being an all or nothing and is basically done with AOE resists anyway

**Comment by PTruscott** [comment]
Last session AOEs were rolled for each person hit (see Soul Spike) as well as individual resistance rolls (See fireball) worked well without slowing down combat

**Comment by PTruscott** [comment]
An issues is missing big abilities when super charging them still - however with more resistance points due to the Large balance patch and the nerf to legendary resistance will probably devalue resistance points generally.  This will hopefully increase turbo-charging usage, and also makes misses less oof.  Still not ideal though

**Comment by Jackington6600** [comment]
Did we consider the idea of adding bonuses to the attack roll (if one is part of the ability) for when resistance points are spent? This can help particular attacks hit while not giving increased crit chance, and reduce the risk of whiffing on a crucial attack that you really want to hit and get the condition off. Something like +3 to the attack roll per resistance point spent?

**Comment by Jackington6600** [comment]
Another solution could be that attack rolls with abilities can't miss, they just deal half damage on a miss.
Could then still crit and maybe only actually miss on a crit fail.
We'd need to check that they're aren't abilities that this causes confusion with or breaks.

Another more drastic idea is to have this half damage on a miss apply to all melee attacks too - if we find melee is quite weak compared to ranged (due to requiring movement, leading to potentially not being able to attack some turns).
