### ISSUE TITLE
Ability Resistance Flexibility & New Resist Costs

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#33]
We should give abilities more choice and generic triggers for bonuses. For example, some abilities could have a choice (your choice) of 2 or 3 resistance types that must be spent by the target to resist the effect. This would allow more tactical choice and ability to coordinate between players. We should also remove some of the overly specific triggers on some abilities, and replace with some that appear more frequently across classes.

With this, some abilities with more powerful affects can perhaps have fewer choices in resistance types. We could also move away from our more strict "2 RESIST for single target" and "1 RESIST for AoE" guidelines, and have some especially strong affects cost 1 to resist even on single target (such as paralyse). These abilities might be considered more like FINISHERS.

Opposed to this, we could have weaker effects (such as prone or immobilise) cost 2 on smaller AoE and 3 on single target. These might be considered OPENERS. 

We could then generally have more OPENERS at low level and FINISHERS at high level but a good mix will be important.

Note that having 0 of a resistance point type now means you CANNOT resist the incoming affect.

**Comment by PTruscott** [comment]
Agreed - the additionally flexibility coming from the resist system rework will allow us to fine tune balance generally a lot better and make the system a lot more intuitive generally.  Overly specific triggers are also kinda lame, so happy to get rid of them.  

With proposed - decision always player choice?  E.g. when they affect you you choose which one you want to spend and when you cast choose which one you want them to spend

**Comment by Jackington6600** [comment]
Yes, always lean towards players choice
