### ISSUE TITLE
Class & Ability Balancing, Polish, & Simplification

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#34]
There's obviously balancing to do. But, we also want to look at simplifying abilities where we can. Making them more user friendly and willing to sacrifice a little uniqueness for more universal behaviours. This will help the game run smoothly.

Within classes and across classes we need to make sure that all of the major play experiences are well catered for, and people can really make what they want and have an enjoyable experience at all levels. We should also help players achieve the gameplay they desire.

This will also include ensuring classes have the right feel and flavour, whilst also considering how they might work together with other classes to some degree - these factors will likely all pull in opposite directions.

We also want to make sure we have a good set of plays and counter plays, and make all abilities super fun :)

**Comment by PTruscott** [comment]
Issue - complete overhaul :') Not quite the specific problems issues were designed for.  But yeah makes sense I guess?

**Comment by PTruscott** [comment]
Issue - complete overhaul :') Not quite the specific problems issues were designed for.  But yeah makes sense I guess?

**Comment by Jackington6600** [comment]
Would you rather start making Jira epics to encapsulate design directions :P this ain't programming and this is the best way to share notes with you.

I'll add more specifics as we work through classes and decide what needs doing, which abilities need improving etc.
