### ISSUE TITLE
Make Healing Great Again

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#35]
Make healing in mortality allow self healing. I know it's against the concept we wanted - but Ian did make a good point that being the only healer and not being able to heal yourself at all feels pretty bad. We could still potentially have self feeling be less - but I'm not sure this is necessary. Then the only question would be if all Tanks would also want to have heals for themselves - I'm not sure.

**Comment by PTruscott** [comment]
Yeah no issues here.  Understand why we wanted to avoid it but it didn't work out and it does feel BAD man from the oneshots I played as a healer.
