### ISSUE TITLE
Initiative Simplification

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#36]
Quite like the idea of whoever initiates starts and the rest is clockwise or something (saw this idea online). A bit wierd but it's very fast to get combat started and keep up game momentum. We've both witnessed how the game kinda drags to a halt when combat starts and initiative needs to be rolled, but really it would make a lot more sense to immediately throw someone into it - start the fight and keep up the tension.

May also make it more intuitive for players to plan turns, and the swing of the game (all enemies go then all players go) might actually be a good thing for generating tension. This would remove initiative from PER but PER is already a generally good stat for ranged attacks and seeing and finding things. 

Alternatively everyone rolls and highest starts, then go clockwise. Or maybe the player who goes first can choose between clockwise and anticlockwise.

**Comment by PTruscott** [comment]
Kinda onboard, defo onboard with simplification tbh and predictability.   You can then start who goes first based on who enters the room first etc so a lot more intuitive.  This might be the sort of thing experienced players don't like though as "uh it's not like this in other games" 

Think it needs to be play tested

**Comment by Jackington6600** [comment]
New idea for initiative: Only players roll against a DC, this DC could be set by the GM on the fly, or predetermined based on the encounter, depending on how fast the players need to be to get a go on the first turn (such as being harder if the players are taken by surprise, or much easier if the players surprise the enemy, or harder if all the enemies are fast). Then start with the player to the left of the GM going clockwise. Each player takes a turn if they beat the DC, and skip a turn if they didn't. Initiative then reaches the GM and they take all the enemy turns. Play then continues clockwise as expected, but now all players get their turn. Players should ideally sit in order of best initiative bonus.

This system allows players to still get to roll to go before enemies, without wasting lots of time recording all the rolled numbers in order. It basically functions the same as normal initiative but slightly simplified, and avoids most scenarios where ALL of the players go first and get a large advantage, or equally but opposite, all the enemies go first.
