### ISSUE TITLE
Spend HP To Resist Effects

### ISSUE THREAD

**Issue by Jackington6600** [Jackington6600/Arcus#37]
A rather rogue idea: we allow players or enemies to spend HP as resistance points of any type - perhaps 6 (or Heavy) HP per resistance point. 

This doesn't have to be a core ability for everyone, could be a legendary ability or just a class specific one. Thought it was generally interesting - the same but opposite of what we already offer.

Only real reason I'm interested in this is to have SOME option to resist things if you don't have RESIST left but really really want to (because we've made it more deterministic again). I imagine this would be more useful for bosses, and even if a player's condition doesn't happen they get to deal bonus damage instead. I don't imagine it would be used that much anyway - it could even just be a BOSS specific rule.

**Comment by PTruscott** [comment]
Defo not Heavy - having it scale as you level up seems to be very bad.  I don't hate the sacrifice HP - might work as an interesting trait to be picked up by people.  I can see Fasier's character taking it as an example.
